export BASH_IT="$HOME/.bash-it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export CUSTOM_THEME_DIR="$HOME/.config/bash-it"
export BASH_IT_THEME='iterate-custom'

# Don't check mail when opening terminal.
unset MAILCHECK

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Load Bash It
source $BASH_IT/bash_it.sh

if [ -d ~/.local-only ]; then
  source ~/.local-only/*.sh
fi

if [ -f ~/.aliases ]; then
  source ~/.aliases
fi
