# Path to the bash it configuration
export BASH_IT="$HOME/.bash-it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='iterate'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
# export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
# export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

if [ -d ~/.local-only ]; then
  source ~/.local-only/*.sh
fi

if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

export NVM_DIR="/Users/clayreimann/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Haskell executables
export PATH=$PATH:$HOME/Library/Haskell/bin
# Stack executables
export PATH=$PATH:$HOME/.local/bin

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/clayreimann/.sdkman"
[[ -s "/Users/clayreimann/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/clayreimann/.sdkman/bin/sdkman-init.sh"

export SSH_AUTH_SOCK=$HOME/.yubiagent/sock